BONUS/GRAFANA_USERS_MANAGEMENT/grafana-users/app/models.py
from app import login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User


class User(UserMixin):

    def __init__(self, user_json):
        self.user_json = user_json

    def get_id(self):
        object_id = self.user_json.get('id')
        return object_id

BONUS/GRAFANA_USERS_MANAGEMENT/grafana-users/app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, Optional


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class AddUserForm(FlaskForm):
    name = StringField('Name (Optional)', validators=[Optional(), Length(min=4)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired(), Length(min=4)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=4)])
    is_admin = BooleanField('Admin')
    submit = SubmitField('Add User')

BONUS/GRAFANA_USERS_MANAGEMENT/grafana-users/app/__init__.py
from flask import Flask
from flask_login import LoginManager
from app.config import Config

login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    login_manager.init_app(app)

    from app.users.routes import users
    from app.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(errors)

    return app

BONUS/GRAFANA_USERS_MANAGEMENT/grafana-users/app/users/routes.py
import os
import sys
from flask import render_template, url_for, flash, redirect, request, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required
from app.models import User
from app.users.forms import LoginForm, AddUserForm
from app.users.utils import search_user, create_user, change_user_permission, delete_user_from_grafana

users = Blueprint('users', __name__)

GRAFANA_HOST = os.environ.get('GRAFANA_HOST')
if not GRAFANA_HOST:
    raise ValueError("Please set environment variable GRAFANA_HOST")


# https://grafana.com/docs/grafana/latest/http_api/user/#search-users
# https://grafana.com/docs/grafana/latest/http_api/admin/#delete-global-user
# https://grafana.com/docs/grafana/latest/http_api/admin/#permissions
# https://grafana.com/docs/grafana/latest/http_api/admin/#global-users

SEARCH_API_URL = f'{GRAFANA_HOST}/api/users'
USERS_API_URL = f'{GRAFANA_HOST}/api/admin/users'


@users.route('/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.add_user'))
    form = LoginForm()
    if form.validate_on_submit():
        status_code, users_list = search_user(url=SEARCH_API_URL, username=form.username.data, password=form.password.data)
        if status_code == 401:
            flash('Invalid username or password', 'danger')
        elif status_code == 403:
            flash('You must be an admin user for adding users', 'danger')
        else:
            session['username'] = form.username.data
            session['password'] = form.password.data
            for user in users_list:
                if user.get('login') == form.username.data:
                    loginuser_json = user
                    if loginuser_json:
                        loginuser = User(loginuser_json)
                        login_user(loginuser, remember=form.remember.data)
                        next_page = request.args.get('next')
                        return redirect(next_page) if next_page else redirect(url_for('users.login'))
                    else:
                        flash('Invalid email or password', 'danger')

    return render_template('login.html', title='Login', form=form)


@users.route('/add_user', methods=['GET', 'POST'])
@login_required
def add_user():
    form = AddUserForm()
    if form.validate_on_submit():
        payload = {
            'name': form.name.data,
            'email': form.email.data,
            'login': form.username.data,
            'password': form.password.data,
            'OrgId': 1
        }
        username = session['username']
        password = session['password']
        status_code, data = create_user(url=USERS_API_URL, username=username, password=password, payload=payload)
        if status_code == 500:
            flash('User already exists', 'warning')
        elif form.is_admin.data:
            user_id = data["id"]
            payload = {
                'isGrafanaAdmin': True
            }
            url = f'{USERS_API_URL}/{user_id}/permissions'
            status_code, data = change_user_permission(url=url, username=username, password=password, payload=payload)
            if status_code != 200:
                url = f'{USERS_API_URL}/{user_id}'
                status_code, data = delete_user_from_grafana(url=url, username=username, password=password)
                flash('Something went wrong!', 'danger')
            else:
                flash('User has been created successfully', 'success')
        else:
            flash('User has been created successfully', 'success')

        return redirect(url_for('users.login'))
    return render_template('add_user.html', title='Add User', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

BONUS/GRAFANA_USERS_MANAGEMENT/grafana-users/app/templates/add_user.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add user to Grafana</legend>
                <!-- Name filed -->
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <!-- Email filed -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <!-- Password Field -->
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.is_admin(class="form-check-input") }}
                    {{ form.is_admin.label(class="form-check-label") }}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

BONUS/GRAFANA_USERS_MANAGEMENT/grafana-users/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

        {% if title %}
        <title>Grafana - Users Management - {{ title }}</title>
        {% else %}
        <title>Grafana - Users Management</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">Grafana - Users Management</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto"></div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <main role="main" class="container">
            <div class="row">
                <div class="col-md-6">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}

                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

BONUS/GRAFANA_USERS_MANAGEMENT/grafana-users/app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In As Admin User</legend>

                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

        </form>
    </div>
{% endblock content %}